# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-10 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170710_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
