# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-07-10 19:42
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('store', '0003_auto_20170710_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='placeholder_description',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='description', to='cms.Placeholder'),
        ),
    ]
